trigger:
- main

pool:
  name: Default

steps:
- task: UnityBuildTask@3
  name: unitybuild
  inputs:
    buildTarget: standalone
    outputPath: $(Build.BinariesDirectory)
    outputFileName: drop

- script: |
    echo $(unitybuild.logsOutputPath)